name = "WooldridgeDatasets"
uuid = "b46f53ff-21ea-4df8-83e7-e19d2972755a"
authors = ["Aru Bhardwaj <arubhardwaj@pm.me>"]
version = "0.1.4"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"

[compat]
julia = "1.7.0"
CSV = "0.10.3"
