name = "WooldridgeDatasets"
uuid = "b46f53ff-21ea-4df8-83e7-e19d2972755a"
authors = ["Aru Bhardwaj <aruecon@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
